M48
; DRILL file {KiCad 7.0.5} date Tue Aug  8 11:46:27 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-08T11:46:27-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.250
%
G90
G05
T1
X120.32Y-152.13
X125.17Y-152.13
T2
X120.02Y-155.16
X125.47Y-155.16
T3
X150.292Y-190.213
X161.722Y-190.213
T0
M30
