M48
; DRILL file {KiCad 7.0.5} date Wed Feb  5 20:03:16 2025
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-05T20:03:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.250
%
G90
G05
T1
X296.787Y-150.383
X301.637Y-150.383
T2
X296.487Y-153.413
X301.937Y-153.413
T3
X276.53Y-180.391
X287.96Y-180.391
T0
M30
